#! /bin/sh

#-- desk --#
# Script to manage multiple montiors.
# Dependencies:
#	- xrandr
# ~ ADIGEN

cd ~/.screenlayout

current=$(cat current)

case "$current" in
	"dual") echo "mirror" > current
	;;
	"mirror") echo "single_main" > current
	;;
	"single_main") echo "single_secondary" > current
	;;
	"single_secondary") echo "dual" > current
	;;
esac

# bspc wm -r
bspc monitor primary -d 1 2 3 4 5
