#! /bin/sh

#-- desk --#
# Script to manage multiple montiors.
# Dependencies:
#	- xrandr
# ~ ADIGEN

cd ~/.screenlayout

current=$(cat current)

case "$current" in
	"dual")
		echo "mirror" > current
		# bspc monitor HDMI-A-0 -d 1 2 3 4 5
		# bspc monitor eDP -d 6
	;;
	"mirror")
		echo "single_main" > current
		# bspc monitor eDP -d 1 2 3 4 5
	;;
	"single_main")
		echo "single_secondary" > current
		# bspc monitor eDP -d 1 2 3 4 5
		# bspc monitor HDMI-A-0 -r
	;;
	"single_secondary")
		echo "dual" > current
		# bspc monitor HDMI-A-0 -d 1 2 3 4 5
		# bspc monitor eDP -r
	;;
esac

bspc monitor primary -d 1 2 3 4 5
