#! /bin/sh

_usage() {
	cat <<EOF
NAME
	ocr - Select screen region and get OCR text copied to clipboard

USAGE
	ocr

DESCRIPTION
	Simple script to OCR text on screen.

DEPENDENCIES
	- maim
	- tesseract
	- tesseract-data-eng (or any other language)
	- dunst (or any notifier which supports notify-send)

AUTHOR
	ADIGEN (https://aadivishnu.com)
EOF
}

scrot='maim -squl -b 3 -m 10 -c 1,0.1,0.1,0.3'
notifier='notify-send'
filenameFormat='%Y-%m-%d-%T.png'
fileSaveLoc=`echo $HOME/Pictures/Screenshots/$(date +${filenameFormat})`
fileCacheLoc="/tmp/screenshot_cache_temp.png"

${scrot} ${fileCacheLoc} &&
tesseract ${fileCacheLoc} stdout | xclip -selection clipboard
${notifier} -t 5000 -r '12345' OCR "Text copied to clipboard"
