#! /bin/sh

#-- open-or-switch-to --#
# Scratchpad functionality but with desktops.
# Launches program if doesn't
# Dependencies:
#   - xdotool
# ~ ADIGEN

# case is overkill here but is nicer to add more options down the line.
case "$1" in
	-h|h|help|--help|'')
		cat <<EOF
Usage: $(basename "${0}") CLASSNAME/TITLE LAUNCH_COMMAND...
EOF
		exit
		;;
esac

windowname=$1
shift
exe=$@

id=$(xdotool search "${windowname}")
if [ -z "${id}" ]; then
	${exe}
else
	while read -r instance; do
		bspc node "${instance}" --focus
	done <<<"${id}"
fi
