#! /bin/sh

#-- pbtoggle --#
# Tiny script to toggle polybar's visibility.
# Dependencies:
#	- polybar
#	- bspwm
# ~ ADIGEN

if [ -f ~/.cache/pbtoggle ]; then 
	polybar-msg cmd show 
	rm ~/.cache/pbtoggle 
else 
	polybar-msg cmd hide 
	bspc config top_padding 0 
	touch ~/.cache/pbtoggle 
fi
