#! /bin/sh

#-- pbtoggle --#
# Tiny script to toggle polybar's visibility.
# Dependencies:
#	- polybar
#	- bspwm
# ~ ADIGEN

if [ -f ~/.cache/pbtoggle ]; then 
	# polybar-msg cmd show 
	pkill -f hideIt.sh
	pbstart &

	bspc config bottom_padding 1
	bspc config window_gap 10

	rm ~/.cache/pbtoggle 
else 
	# polybar-msg cmd hide 
	# switch to overlay polybar
	POLYBAR_BAR=top pbstart &
	hideIt.sh --name '^polybar-top' --hover -d bottom -p 1 --wait &
	hideIt.sh --name '^polybar-top_eDP' --hover -d bottom -p 1 --wait &

	sleep 0.3

	bspc config top_padding 0
	bspc config bottom_padding 1
	# bspc config window_gap 0

	touch ~/.cache/pbtoggle 
fi
