#! /bin/sh

#-- sound --#
# Script to change sound related settings.
# Dependencies:
#	- dunst
#	- amixer (alsa-utils)
# ~ ADIGEN

alias amixer='amixer -D hw:1'

case "${1}" in
"increase")
	pactl set-sink-volume @DEFAULT_SINK@ +5% && dunstify -t 500 -u low -r '92813' -h int:value:$(pactl get-sink-volume @DEFAULT_SINK@ | awk -F' ' '/%/ { print $5 }') "Volume"
	# pactl set-sink-volume @DEFAULT_SINK@ +5% && dunstify -t 500 -u low -r '92813' "Volume: $(pactl get-sink-volume @DEFAULT_SINK@ | awk -F' ' '/%/ { print $5 }')"
	;;
"decrease")
	pactl set-sink-volume @DEFAULT_SINK@ -5% && dunstify -t 500 -u low -r '92813' -h int:value:$(pactl get-sink-volume @DEFAULT_SINK@ | awk -F' ' '/%/ { print $5 }') "Volume"
	# pactl set-sink-volume @DEFAULT_SINK@ -5% && dunstify -t 500 -u low -r '92813' "Volume: $(pactl get-sink-volume @DEFAULT_SINK@ | awk -F' ' '/%/ { print $5 }')"
	;;
"mute")
	amixer sset Master toggle
	dunstify -t 500 -u low -r '92813' "Volume $(amixer sget Master | awk -F '[][]' '/dB/ {print $6}')"
	;;

"mic")
	pactl set-source-mute alsa_input.pci-0000_04_00.6.HiFi__Mic1__source toggle && dunstify -t 500 -u low -r '92813' "Mic $(pactl get-source-mute alsa_input.pci-0000_04_00.6.HiFi__Mic1__source)"
	#amixer set Capture toggle; dunstify -t 500 -u low -r '92813' "Mic $(amixer get Capture | awk -F'[][]' '/Left:/ {print $6}')"
	;;
esac
