#! /bin/zsh

#-- updots --#
# A script to sync all my submodules
# and main dotfiles back to Github.
# Dependencies:
#   - git
# ~ ADIGEN

# Exit on any error
set -e
alias dots="/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME"

# Filter packages

# This one only counts packages the minimal way.
# For eg, package `nvidia` installs `xorg-server`.
# So `xorg-server` will not be added to the list.
# If you remove `nvidia` from packages, pacman won't install `xorg-server` because it wasn't in the list.
#pacman -Qqtte > ~/Documents/Extra/packages
# This one counts all explicitly installed packages.
pacman -Qqe > ~/Documents/Extra/packages

# Filter for portable packages (no heavy dependencies)
grep -Fvxf ~/Documents/Extra/packages.extra ~/Documents/Extra/packages > ~/Documents/Extra/packages.portable

# updots on submodules
dots submodule foreach 'git commit -am "updots" || true'
dots submodule foreach 'git push || true'

# Push main
dots commit -am 'updots'
dots push
